/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ChatScriptJNI {
  public final static native int InitSystem__SWIG_0(int jarg1, long jarg2, String jarg3, String jarg4, String jarg5);
  public final static native int InitSystem__SWIG_1(int jarg1, long jarg2, String jarg3, String jarg4);
  public final static native int InitSystem__SWIG_2(int jarg1, long jarg2, String jarg3);
  public final static native int InitSystem__SWIG_3(int jarg1, long jarg2);
  public final static native void PerformChat(String jarg1, String jarg2, String jarg3, String jarg4, String jarg5);
}
