/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ChatScript {
  public static int InitSystem(int argc, SWIGTYPE_p_p_char argv, String unchangedPath, String readonlyPath, String writablePath) {
    return ChatScriptJNI.InitSystem__SWIG_0(argc, SWIGTYPE_p_p_char.getCPtr(argv), unchangedPath, readonlyPath, writablePath);
  }

  public static int InitSystem(int argc, SWIGTYPE_p_p_char argv, String unchangedPath, String readonlyPath) {
    return ChatScriptJNI.InitSystem__SWIG_1(argc, SWIGTYPE_p_p_char.getCPtr(argv), unchangedPath, readonlyPath);
  }

  public static int InitSystem(int argc, SWIGTYPE_p_p_char argv, String unchangedPath) {
    return ChatScriptJNI.InitSystem__SWIG_2(argc, SWIGTYPE_p_p_char.getCPtr(argv), unchangedPath);
  }

  public static int InitSystem(int argc, SWIGTYPE_p_p_char argv) {
    return ChatScriptJNI.InitSystem__SWIG_3(argc, SWIGTYPE_p_p_char.getCPtr(argv));
  }

  public static void PerformChat(String user, String usee, String incoming, String ip, String output) {
    ChatScriptJNI.PerformChat(user, usee, incoming, ip, output);
  }

}
